config/routes.rb
Depot::Application.routes.draw do
  resources :details

  resources :customs

  resources :users

  get 'admin' => 'admin#index'
  get 'success' => 'orders#success'
  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
    get "cuslogin" => :cuslogin
    post "cuslogin" => :mylogin
  end
  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  get 'ad' => 'store#ad'

  resources :products do
    get :who_bought, :on => :member
  end

  root :to => 'store#index', :as => 'store'

end

app/models/custom.rb
class Custom < ActiveRecord::Base
	validates :name, :password, :presence => true
	has_many :orders
	has_many :details
	class << self
    def authenticate(name, password)
      if custom = find_by_name(name)
        if custom.password == password
          custom
        end
      end
    end
  end
end

app/controllers/customs_controller.rb
class CustomsController < ApplicationController
  before_action :set_custom, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize, :only =>[:new, :create, :show, :edit, :update]
  # GET /customs
  # GET /customs.json
  def index
    @customs = Custom.all
  end

  # GET /customs/1
  # GET /customs/1.json
  def show
    @details = current_custom.details
  end

  # GET /customs/new
  def new
    @custom = Custom.new
  end

  # GET /customs/1/edit
  def edit
  end

  # POST /customs
  # POST /customs.json
  def create
    @custom = Custom.new(custom_params)

    respond_to do |format|
      if @custom.save
        session[:custom_id] = @custom.id
        format.html { redirect_to @custom, notice: '注册成功.' }
        format.json { render action: 'show', status: :created, location: @custom }
      else
        format.html { render action: 'new' }
        format.json { render json: @custom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customs/1
  # PATCH/PUT /customs/1.json
  def update
    respond_to do |format|
      if @custom.update(custom_params)
        format.html { redirect_to @custom, notice: '修改成功.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @custom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customs/1
  # DELETE /customs/1.json
  def destroy
    @custom.destroy
    respond_to do |format|
      format.html { redirect_to customs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom
      @custom = Custom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_params
      params.require(:custom).permit(:name, :password)
    end
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/views/customs/_form.html.erb
<%= form_for(@custom) do |f| %>
  <% if @custom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom.errors.count, "error") %> prohibited this custom from being saved:</h2>

      <ul>
      <% @custom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-md-6">    
      <div class="input-group">
        <span class="input-group-addon">用户名</span>
        <%= f.text_field :name, class:"form-control", 
            placeholder:"请输入用户名"%>
      </div>
    </div>
  </div>
  <div class="row form-group">
    <div class="col-md-6">    
      <div class="input-group">
        <span class="input-group-addon">密 码</span>
        <%= f.password_field :password, class:"form-control", 
            placeholder:"请输入密码"%>
      </div>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-1 pull-left">
      <div class="actions">
        <button type="submit" class="btn btn-default" name="submit">确认</button>
      </div>
    </div>
    
  </div>
<% end %>

app/views/customs/edit.html.erb
<h1>编辑个人资料</h1>

<%= render 'form' %>

app/views/customs/index.html.erb
<h1>用户列表</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>姓名</th>
      <th>密码</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customs.each do |custom| %>
      <tr class="<%= cycle('list_line_odd','list_line_even') %>">
        <td><%= custom.name %></td>
        <td><%= custom.password %></td>
        <td><%= link_to '查看', custom %></td>
        <td><%= link_to '编辑', edit_custom_path(custom) %></td>
        <td><%= link_to '删除', custom, method: :delete, data: { confirm: '你确定 ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '添加用户', new_custom_path, class:"h2" %>

app/views/customs/new.html.erb
<h1>注册</h1>

<%= render 'form' %>

app/views/customs/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row show-grid">
    <div class="col-md-2"><h2>你好</h2></div>
    <div class="col-md-6"><h2><%= @custom.name %></h2></div>
</div>
<div class=""></div>
<%= link_to '编辑个人资料', edit_custom_path(@custom), class:"h2" %><br/>
<table class="table table-striped">
  <thead>
    <tr>
      <th>收货人姓名</th>
      <th>地址</th>
      <th>联系电话</th>
      <!-- <th>默认地址</th> -->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr class="<%= cycle('list_line_odd','list_line_even') %>">
        <td><%= detail.name %></td>
        <td><%= detail.addr %></td>
        <td><%= detail.contach %></td>
        <!-- <td><%= detail.defau %></td> -->
        <td><%= link_to '查看', detail %></td>
        <td><%= link_to '编辑', edit_detail_path(detail) %></td>
        <td><%= link_to '删除', detail, method: :delete, data: { confirm: '确定删除?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '新增收货地址', new_detail_path, class:"h2" %>