config/routes.rb
Depot::Application.routes.draw do
  resources :details

  resources :customs

  resources :users

  get 'admin' => 'admin#index'
  get 'success' => 'orders#success'
  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
    get "cuslogin" => :cuslogin
    post "cuslogin" => :mylogin
  end
  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  get 'ad' => 'store#ad'

  resources :products do
    get :who_bought, :on => :member
  end

  root :to => 'store#index', :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
      #current_item.price = current_item.product.price
    end
    current_item
  end

  def total_price
    line_items.to_a.sum{|item| item.total_price}
  end
end

app/models/custom.rb
class Custom < ActiveRecord::Base
	validates :name, :password, :presence => true
	has_many :orders
	has_many :details
	class << self
    def authenticate(name, password)
      if custom = find_by_name(name)
        if custom.password == password
          custom
        end
      end
    end
  end
end

app/models/detail.rb
class Detail < ActiveRecord::Base
	validates :defau, :default => false
	validates :name, :addr, :contach, :presence => true
	belongs_to :custom
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :name, :address, :contach, :pro, :presence => true
  has_many :line_items, :dependent => :destroy
  belongs_to :custom
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  has_many :line_items
  has_many :orders, :through => :line_items
  #...
  before_destroy :ensure_not_referenced_by_any_line_item


  # validation stuff...
  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  #
  validates :image_url, :format => {
      :multiline => true,
      :with    => %r{\.(gif|jpg|png)$}i,
      :message => 'must be a URL for GIF, JPG or PNG image.'
  }
  
  private
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  validate :password_must_be_present
  after_destroy :ensure_an_admin_remains
  
  attr_accessor :password_confirmation
  attr_reader :password

  class << self
    def authenticate(name, password)
      if user = find_by_name(name)
        if user.hashed_password == encrypt_password(password, user.salt)
          user
        end
      end
    end
    
    def encrypt_password(password, salt)
      Digest::SHA2.hexdigest(password + "wibble" + salt)
    end
  end

  def password=(password)
    @password = password
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

  private
  def password_must_be_present
    errors.add(:password, "请输入密码") unless hashed_password.present?
  end
  
  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, :only => [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart =Cart.find(params[:id])
    rescue ActivrRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url,:notice => 'Invalid cart'
    else
      respond_to do |format|
        format.html
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to(store_url) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>你好 管理员</h1>
现在 <%= Time.now %>
总共有 <%= @total_orders%> 笔订单需要处理

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Depot Store</title>
      <link href="/assets/bootstrap.min.css" media="screen" rel="stylesheet" />
      <link href="/assets/component.css" media="screen" rel="stylesheet" />
      <link href="/assets/depot.css" media="screen" rel="stylesheet" />
      <link href="/assets/scaffolds.css" media="screen" rel="stylesheet" /> 
      <script src="/assets/jquery.js"></script>
      <script src="/assets/jquery_ujs.js"></script>
      <script src="/assets/jcarousellite_1.0.1.min.js"></script>
      <script src="/assets/modernizr.custom.js"></script>
      <script src="/assets/mystyle.js"></script> 
    <%= csrf_meta_tags %>
    <link type="image/x-icon" href="../images/favicon.png" rel="shortcut icon">
  </head>
<body>
  <div class="container">
  <nav class="navbar navbar-default nav-set" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="logo pull-left"></div>
    <div class="navbar-header">
      <%= link_to "首页", store_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if session[:user_id] %>
      <ul class="nav navbar-nav">
        <li><%= link_to "订单", orders_path %></li>
        <li><%= link_to "商品", products_path %></li>
        <li><%= link_to "用户", customs_path %></li>
        <li><%= link_to "管理者", users_path %></li>
        <li><%= button_to "退出", logout_path, method: :delete, class: "btn btn-default navbar-btn" %></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav">
        <% if session[:custom_id] %>
        <li><%= link_to '账户管理', @custom %></li>
        <li><%= button_to "退出", logout_path, method: :delete, class: "btn btn-default navbar-btn" %></li>
        <% else %>
        <li><%= link_to "登陆", cuslogin_path %></li>
        <% end %>
      </ul>
      <% end %>
      
      <div class="weather pull-right">
        <iframe src="http://m.weather.com.cn/m/pn4/weather.htm " width="160" height="20" marginwidth="0"   marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>      
      </div>
    </div>
  </nav>  
  <div class="row sub-set">
    <div class="col-md-4 ">
      <div class="slideshow-list">
        <ul>
          <li><span class='toptext'><%= link_to 'Search', {controller:"store",action:"index", search:""} %></span></li><li><span class='toptext'><a href='http://www.feilook.com/thespace-a512.html' target='_blank'>TOPMAN LUX 2013秋冬</a></span></li><li><span class='toptext'><a href='http://www.feilook.com/thespace-a513.html' target='_blank'>THE WAY WE WEAR THEM</a></span></li><li><span class='toptext'><a href='http://www.feilook.com/thespace-a509.html' target='_blank'>BEST IN SHOW</a></span></li><li><span class='toptext'><a href='http://www.feilook.com/thespace-a507.html' target='_blank'>Topshop Unique 2014春夏秀场</a></span></li><li><span class='toptext'><a href='http://www.feilook.com/thespace-a506.html' target='_blank'>Mary Katrantzou 的裙上风景</a></span></li> 
        </ul>
        <span class="prev-top">▲</span>
        <span class="next-top">▼</span>
      </div>
    </div>
    <div class="col-md-5 col-md-offset-3">
      <form class="form-inline" role="search" method="get" action=
                   "<%= store_path %>">
        <div class="form-group">
            <input type="text" class="form-control" name="search" placeholder="输入商品进行搜索" style="width:25em;">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
      <div class="search_hot">热门搜索：
        <%= link_to '数码', {controller:"store",action:"index", search:"数码"} %>
        <%= link_to '图书', {controller:"store",action:"index", search:"图书"} %>
        <%= link_to '包', {controller:"store",action:"index", search:"包"} %>
        <%= link_to '鞋', {controller:"store",action:"index", search:"鞋"} %>
      </div>
    </div>
  </div>

    <div class="row">
      <div class="col-md-3">
          <div class="well nav-set">
            <div>
              <% if @cart %>
                <div id="cart" <% if @cart.line_items.empty? %>  style="display: none" <% end %> >
                 <%= render @cart %>
                </div>
              <% end %>
            </div> 
            <ul class="nav nav-list">
              <li class="nav-header">图书.家电.数码</li>
              <li>
                <%= link_to '数码', {controller:"store",action:"index", search:"数码"} %>
              </li>
              <li>
                <%= link_to '图书', {controller:"store",action:"index", search:"图书"} %>
              </li>
              <li>
                <%= link_to '家电', {controller:"store",action:"index", search:"家电"} %>
              </li>
              <li class="nav-header">服饰.化妆品.箱包</li>
              <li>
                <%= link_to '服饰', {controller:"store",action:"index", search:"服饰"} %>
              </li>
              <li>
                <%= link_to '鞋', {controller:"store",action:"index", search:"鞋"} %>
              </li>
              <li>
                <%= link_to '包', {controller:"store",action:"index", search:"包"} %>
              </li>
              <li class="nav-header">食品</li>
              <li>
                <%= link_to '酒水.饮料', {controller:"store",action:"index", search:"酒水.饮料"} %>
              </li>
              <li>
                <%= link_to '零食', {controller:"store",action:"index", search:"零食"} %>
              </li>
              <li>
                <%= link_to '其他', {controller:"store",action:"index", search:""} %>
              </li>
            </ul>
          </div><!--/.well -->
      </div>
      <div class="col-md-9">
        <%= yield %>
      </div>
    </div>  
    <blockquote>
      <div class="footer">
        <hr>
        <div class="center">
          <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more">分享到：</a><a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina">新浪微博</a><a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone">QQ空间</a><a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren">人人网</a><a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin">微信</a></div>
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"http://depotstore.herokuapp.com 谢谢你的支持","bdMini":"1","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"24"},"share":{"bdSize":16}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
        </div>
        <div class="copyright pull-right">
          Copyright©depotstore.herokuapp.com All Rights Reserved         
        </div>
        <br/>
      </div>
    </blockquote> 
  </div>
</body>
</html>

app/views/notifier/order_receiver.text.erb
Dear <%= @order.name %>

<%= @greeting %>, find me in app/views/app/views/notifier/order_receiver.text.erb

app/views/notifier/order_shipped.text.erb
Notifier#order_shipped

<%= @greeting %>, find me in app/views/app/views/notifier/order_shipped.text.erb